AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::IoT::BillingGroup resource type

Globals:
  Function:
    Timeout: 240  # docker start-up times can be long for SAM CLI
    MemorySize: 512

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.iot.billinggroup.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/aws-iot-billinggroup-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.iot.billinggroup.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/aws-iot-billinggroup-handler-1.0-SNAPSHOT.jar
