AWSTemplateFormatVersion: 2010-09-09
Description: Thing group stack required for contract tests
Resources:
  ContractTestThingGroupParent:
    Type: 'AWS::IoT::ThingGroup'
    Properties:
      ThingGroupName: CfnContractTestThingGroupParent
      ThingGroupProperties:
        ThingGroupDescription: test ThingGroup for Cfn Contract Tests
      Tags:
        - Key: testTagKey
          Value: tagValue
